version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3.9.13-management
    container_name: 'rabbitmq'
    ports:
      - '15672:15672'
    expose:
      - 5672
    networks:
      - rabbitmq_net
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 10s
      retries: 3
  feedparser:
    container_name: 'feed-parser-service'
    build:
      dockerfile: Dockerfile
      context: ./
    command: sh -c '/bin/wait-for-it.sh rabbitmq:5672 --timeout=30 ./server'
    ports:
      - '8080:8080'
    environment:
      - RABBITMQ_HOST=rabbitmq:5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
      - ENV=Production
    depends_on:
      - "rabbitmq"
    networks:
      - rabbitmq_net
    restart: always

networks:
  rabbitmq_net:
    driver: bridge
