global:
  scrape_interval:     10s
  evaluation_interval: 10s
scrape_configs:
  - job_name: 'feed-parser'
    static_configs:
      - targets: ['feedparser:8080']
        labels:
          group: 'feed-parser'
rule_files:
  - 'prometheus.rules.yml'
